name: playerinfo
aliases:
  - pi
  - myinfo
  - status
description: Display player information
help_text: |
  PLAYERINFO - Show information about your captain
  PLAYERINFO <name> - Show information about another captain
context_requirements:
  - not_dead
error_messages: {}
